import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const OPENAPI_URL = "https://rest.runpod.io/v1/openapi.json";
const GRAPHQL_URL = "https://api.runpod.io/graphql";
const OPENAPI_PATH = "src/openapi.json";
const OUTPUT_PATH = "src/runpod-api.ts";
const GPU_TYPES_PATH = "src/runpod-gpu-types.ts";

const openApiRes = await fetch(OPENAPI_URL);
const schema = (await openApiRes.json()) as {
  paths: Record<string, { post?: { operationId?: string } }>;
};

// Fix duplicate operationIds
// RunPod's API has PATCH and POST synonyms with the same operationId for /update paths
for (const [path, methods] of Object.entries(schema.paths)) {
  if (path.endsWith("/update") && methods.post?.operationId) {
    methods.post.operationId += "ViaPost";
  }
}

writeFileSync(OPENAPI_PATH, JSON.stringify(schema));

execSync(`npx openapi-typescript ${OPENAPI_PATH} -o ${OUTPUT_PATH}`, {
  stdio: "inherit",
});

// GraphQL is the source of truth for GPU / CPU catalogue. RunPod's REST
// OpenAPI schema lags behind on SKUs (e.g. it omitted RTX PRO 4500 Blackwell
// and cpu3m/cpu5m), and pod creation for missing GPUs is actually rejected
// server-side by REST's strict enum validation. We emit the up-to-date lists
// here so callers get accurate types and the GraphQL pod-create path has a
// canonical GpuTypeId union.
const gqlRes = await fetch(GRAPHQL_URL, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    query: "{ gpuTypes { id } cpuFlavors { id } dataCenters { id } }",
  }),
});
const gql = (await gqlRes.json()) as {
  data?: {
    gpuTypes?: { id: string }[];
    cpuFlavors?: { id: string }[];
    dataCenters?: { id: string }[];
  };
  errors?: unknown;
};
if (!gql.data?.gpuTypes || !gql.data.cpuFlavors || !gql.data.dataCenters) {
  throw new Error(`GraphQL catalogue query failed: ${JSON.stringify(gql)}`);
}
// RunPod returns "unknown" as a catch-all placeholder; drop it so it does
// not show up in IDE autocomplete.
const gpuIds = gql.data.gpuTypes
  .map((g) => g.id)
  .filter((id) => id !== "unknown")
  .sort();
const cpuIds = gql.data.cpuFlavors
  .map((c) => c.id)
  .filter((id) => id !== "unknown")
  .sort();

const dcIds = gql.data.dataCenters
  .map((d) => d.id)
  .filter((id) => id !== "unknown")
  .sort();

const unionLines = (ids: string[]) =>
  ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n");

const gpuTypesModule = `// Auto-generated by scripts/generate-api-types.ts. Do not edit.
// Sourced from RunPod GraphQL \`gpuTypes\`, \`cpuFlavors\`, and \`dataCenters\` queries,
// which stay ahead of the REST OpenAPI enum.
export type GpuTypeId =
${unionLines(gpuIds)};

export type CpuFlavorId =
${unionLines(cpuIds)};

export type DataCenterId =
${unionLines(dcIds)};
`;
writeFileSync(GPU_TYPES_PATH, gpuTypesModule);

execSync(
  `npx prettier --write ${OUTPUT_PATH} ${OPENAPI_PATH} ${GPU_TYPES_PATH}`,
  { stdio: "inherit" },
);
